server:
  port: 8082
  servlet:
    context-path: /wechatApp


##############################################
#
# mybatis配置
#
##############################################
#定义实体类的位置
mybatis:
  type-aliases-package: com.dss.wechatApp.entity
#定义mybatis中的映射xml文件的位置
  mapper-locations:
  - classpath:mapper/**/*.xml
#开启驼峰命名转换:Table{create_time} -> Entity{createTime}，这样在查询的时候容器才能调用实体类的get,set方法给bean注值
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    use-column-label: true
  

############################################################
#
# 配置数据源，这里使用的是c3p0数据源
#
############################################################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    
##############################################
#
#配置devtools热部署
#
##############################################
#启动热部署
  devtools:
    restart:
      enabled: true
#设置热部署时，重启的目录，添加哪个目录的文件需要restart
      additional-paths:
      - src/main/java
